using System.Runtime.InteropServices;
using Genbox.FastHash.AesniHash;

namespace Genbox.FastHash.Tests.Single;

public class AesniHashTests
{
    // Generated by compiling upstream src/aesni-hash.h (PeterRK/PageBloomFilter, ae11846) and calling
    // AESNI_Hash128 over CreateData(length). Upstream picks between a greedy and a byte-wise tail read
    // depending on page position; both were checked to produce these values. Lengths cover the 1-15 byte
    // tails, the 16-byte mix loop, and the 64-byte block loop taken for lengths above 80.
    private static readonly UpstreamVector[] UpstreamVectors =
    [
        new UpstreamVector(0, 0x00000000U, 0x07a76bdd0807fb1fUL, 0xf1a4624f38048cbeUL),
        new UpstreamVector(1, 0x00000000U, 0x2b57d562978da3e2UL, 0x1c283abefe0c8647UL),
        new UpstreamVector(2, 0x00000000U, 0x8305e59c69ed6c63UL, 0x4f6c4dd24ca7da7cUL),
        new UpstreamVector(3, 0x00000000U, 0xc76bfcda7c707055UL, 0xbaf10335aa148fd3UL),
        new UpstreamVector(4, 0x00000000U, 0x31ce25af4cc5478aUL, 0xf0b86b750a8d65ddUL),
        new UpstreamVector(5, 0x00000000U, 0xe356e3c12252c849UL, 0xf3c21e2a38a775f6UL),
        new UpstreamVector(6, 0x00000000U, 0x3700519708aa34f8UL, 0x8ff2b8bb00db327cUL),
        new UpstreamVector(7, 0x00000000U, 0xb2c4bcdfe9a6ee29UL, 0x69edf3690f1ea1e4UL),
        new UpstreamVector(8, 0x00000000U, 0x641c48c9be8d3af5UL, 0xd0496c525e350313UL),
        new UpstreamVector(9, 0x00000000U, 0x822db3b9c7498fb6UL, 0xb589e779ff49ef4aUL),
        new UpstreamVector(10, 0x00000000U, 0xd3c3a96103992da7UL, 0xc945282f6a32b0abUL),
        new UpstreamVector(11, 0x00000000U, 0x69159c69d66b6f98UL, 0x7be863a9f7968ad1UL),
        new UpstreamVector(12, 0x00000000U, 0x551995718f483a73UL, 0x76f15e1f9750fc46UL),
        new UpstreamVector(13, 0x00000000U, 0x733de6c5da164254UL, 0xd8080b3abfe4670dUL),
        new UpstreamVector(14, 0x00000000U, 0xdb7054d84969a3a7UL, 0x0f926fd58e4d8fa2UL),
        new UpstreamVector(15, 0x00000000U, 0x18e72ee9255a6f5aUL, 0xfd7822ddfc424077UL),
        new UpstreamVector(16, 0x00000000U, 0x07d92d0471466623UL, 0x4561b5f37683bfd6UL),
        new UpstreamVector(17, 0x00000000U, 0x91f02b7188e50f48UL, 0x90a365fbf301cb68UL),
        new UpstreamVector(23, 0x00000000U, 0x47728385025f4338UL, 0xf9f4c12ce4c2b1d5UL),
        new UpstreamVector(24, 0x00000000U, 0x4e996c59f5ab4b29UL, 0x71b5fd3387359a36UL),
        new UpstreamVector(31, 0x00000000U, 0x25d9c57cb58cc804UL, 0x40d1f38ef8bc9816UL),
        new UpstreamVector(32, 0x00000000U, 0x03fc0d01d8332c76UL, 0x4a61ccbb19996a88UL),
        new UpstreamVector(33, 0x00000000U, 0xc9594c3c2ea8596dUL, 0x274f8c5187447f48UL),
        new UpstreamVector(47, 0x00000000U, 0x0ce703500ce001d6UL, 0xd75d3c70d791e676UL),
        new UpstreamVector(48, 0x00000000U, 0x0e6ad1db2504451eUL, 0x75a9de94cdec9be0UL),
        new UpstreamVector(63, 0x00000000U, 0xdb8b38754eb8d45cUL, 0xb94c676d909ffbf9UL),
        new UpstreamVector(64, 0x00000000U, 0xc6c7460075a30fabUL, 0x710881e72e2bc08eUL),
        new UpstreamVector(65, 0x00000000U, 0x66b73691476ca8beUL, 0xc3a3e4b5a7252e32UL),
        new UpstreamVector(79, 0x00000000U, 0xe056603da73bf877UL, 0xb8c8ac7533ac6566UL),
        new UpstreamVector(80, 0x00000000U, 0xa9c6231410fecfc6UL, 0xe6c13718fc84c6deUL),
        new UpstreamVector(81, 0x00000000U, 0x630fa44b41a75a29UL, 0x15aae6474e71b70cUL),
        new UpstreamVector(95, 0x00000000U, 0x9c39e55d0ae97e56UL, 0xaa88e3ed43d39a9eUL),
        new UpstreamVector(96, 0x00000000U, 0x254b3db99cb77990UL, 0xce5598462be07bb6UL),
        new UpstreamVector(97, 0x00000000U, 0xec266861e591cfe2UL, 0xef01ddbf63df970aUL),
        new UpstreamVector(111, 0x00000000U, 0x761e53e65d50d2ceUL, 0x686ee0c388a1c4aeUL),
        new UpstreamVector(112, 0x00000000U, 0x6ffccf49c00d996fUL, 0x3df4871f99590e73UL),
        new UpstreamVector(127, 0x00000000U, 0x07af23eeb8c1f706UL, 0x2cf0b9159d3902b0UL),
        new UpstreamVector(128, 0x00000000U, 0xd516dd9758b6b411UL, 0x49e313dca11d2c16UL),
        new UpstreamVector(143, 0x00000000U, 0xd971342c4aac53c9UL, 0xedb870be820f4a3dUL),
        new UpstreamVector(144, 0x00000000U, 0xbbca23b4618a596eUL, 0x9b46719a2b29910fUL),
        new UpstreamVector(145, 0x00000000U, 0x34fe8fe407f8dafbUL, 0x3bf3c6b4277a282bUL),
        new UpstreamVector(159, 0x00000000U, 0xc2c20bca45c9f50dUL, 0x65c5a623cd46736cUL),
        new UpstreamVector(160, 0x00000000U, 0xe7d2684303f0ed6fUL, 0xf6173e3824291e17UL),
        new UpstreamVector(161, 0x00000000U, 0x3cada72f26728504UL, 0x991ba5657b1fed3dUL),
        new UpstreamVector(255, 0x00000000U, 0x3065bcfd5223e878UL, 0x4a2c4c0cc5b2f0b5UL),
        new UpstreamVector(256, 0x00000000U, 0xfbc44db651ebf953UL, 0xb50444dd1c8cf846UL),
        new UpstreamVector(257, 0x00000000U, 0x618e2188b947a8afUL, 0xcc920aaa95fd7d99UL),
        new UpstreamVector(1000, 0x00000000U, 0xa0e067cf97ce2dccUL, 0x9fab8f7e0a817801UL),
        new UpstreamVector(4096, 0x00000000U, 0x96ceec4196f93ba6UL, 0xf03c2f6b8d95d892UL),
        new UpstreamVector(0, 0x9e3779b9U, 0x8e19f48228061698UL, 0xc1bf883bbecf9e4fUL),
        new UpstreamVector(1, 0x9e3779b9U, 0xbfc3b75ba2b9c720UL, 0x2f1f2801a8405b63UL),
        new UpstreamVector(2, 0x9e3779b9U, 0x7c4c9cd7322f0257UL, 0xad28bc8f1466dc0bUL),
        new UpstreamVector(3, 0x9e3779b9U, 0x34512f35b7aff806UL, 0x3532f426ecc06ae0UL),
        new UpstreamVector(4, 0x9e3779b9U, 0x14adf8d2d3d95618UL, 0x8e2f1ba257154e6aUL),
        new UpstreamVector(5, 0x9e3779b9U, 0xfafdbdd17edf6e76UL, 0x211fdeb00419f28aUL),
        new UpstreamVector(6, 0x9e3779b9U, 0x62ff0cb652313e35UL, 0xe954be06e36992d7UL),
        new UpstreamVector(7, 0x9e3779b9U, 0x2fc1d015cd66123fUL, 0xdde734b20b28f218UL),
        new UpstreamVector(8, 0x9e3779b9U, 0x6f1bc9ad32408003UL, 0x983b2e04eb9c87bfUL),
        new UpstreamVector(9, 0x9e3779b9U, 0x1799f76626f2d56cUL, 0xdbc63bd6f0c7bb8aUL),
        new UpstreamVector(10, 0x9e3779b9U, 0x4dbf46de97bd123bUL, 0xf1ce009928c13eb6UL),
        new UpstreamVector(11, 0x9e3779b9U, 0x2027a1c2ac3082c2UL, 0x9e267aefcf122ef5UL),
        new UpstreamVector(12, 0x9e3779b9U, 0x121f79f881a606a4UL, 0x3f3b4280625ba149UL),
        new UpstreamVector(13, 0x9e3779b9U, 0x7d20673180a6c36dUL, 0x6d783504e7c4c2a2UL),
        new UpstreamVector(14, 0x9e3779b9U, 0xeb204ecb353d237aUL, 0x33db33be63e860ecUL),
        new UpstreamVector(15, 0x9e3779b9U, 0x9b7d6a515c5dc877UL, 0xfcb40fcbaeda50a1UL),
        new UpstreamVector(16, 0x9e3779b9U, 0x3dcf43b2740edaf4UL, 0xdadfb0cd9595d55cUL),
        new UpstreamVector(17, 0x9e3779b9U, 0xfc3a6b452faeb848UL, 0x3a2b802f220f6662UL),
        new UpstreamVector(23, 0x9e3779b9U, 0x24fb784c90c4f7f2UL, 0xf573923febef6713UL),
        new UpstreamVector(24, 0x9e3779b9U, 0x7f6c106d7427755dUL, 0x3243c55fb649544dUL),
        new UpstreamVector(31, 0x9e3779b9U, 0x1293a576fff774cbUL, 0xd2f2e781d4ed1261UL),
        new UpstreamVector(32, 0x9e3779b9U, 0xc7af42619b89d5c6UL, 0x91ffb48fb6617e7eUL),
        new UpstreamVector(33, 0x9e3779b9U, 0x952b51840119cf8dUL, 0xae729a14fafe7087UL),
        new UpstreamVector(47, 0x9e3779b9U, 0x9e712597d0160619UL, 0x77c6be9569c93399UL),
        new UpstreamVector(48, 0x9e3779b9U, 0x3376582830f745b3UL, 0x923c656455ff0447UL),
        new UpstreamVector(63, 0x9e3779b9U, 0x0346f9bd6f284c38UL, 0xbc88e3dfadc9d64bUL),
        new UpstreamVector(64, 0x9e3779b9U, 0xca52d4a3be9ffdf9UL, 0x7320bbcbf6bbaf0bUL),
        new UpstreamVector(65, 0x9e3779b9U, 0x5056a3aecfded8f7UL, 0x33238e21eb95690aUL),
        new UpstreamVector(79, 0x9e3779b9U, 0x762c1dff73fa5435UL, 0xadebb1e4648a358bUL),
        new UpstreamVector(80, 0x9e3779b9U, 0x435152ddae502cf5UL, 0x5f4ee5c30ab1bc38UL),
        new UpstreamVector(81, 0x9e3779b9U, 0x333e525467385148UL, 0x899e1a64122db293UL),
        new UpstreamVector(95, 0x9e3779b9U, 0xfc1f4d51cb85fe15UL, 0x90cab15cc61c9680UL),
        new UpstreamVector(96, 0x9e3779b9U, 0x18c217cd958b13d5UL, 0x0b6c5b2796aee2a7UL),
        new UpstreamVector(97, 0x9e3779b9U, 0x781b89d217cc14e9UL, 0x876ff61c69b0baeaUL),
        new UpstreamVector(111, 0x9e3779b9U, 0x553683989c88304aUL, 0x33f930e34e924bfdUL),
        new UpstreamVector(112, 0x9e3779b9U, 0xaab0bf817d56a780UL, 0xdbd9464d32e00f39UL),
        new UpstreamVector(127, 0x9e3779b9U, 0x710f41428c2a1504UL, 0x67e4f1ed9415b466UL),
        new UpstreamVector(128, 0x9e3779b9U, 0x3744476974a8fc94UL, 0xd3d6bd6c7a3f31d8UL),
        new UpstreamVector(143, 0x9e3779b9U, 0x15c4dd7215ba3346UL, 0xcab4a3bfcbe6db7dUL),
        new UpstreamVector(144, 0x9e3779b9U, 0xc3265d567a16e1e4UL, 0xc6838e69a87104aaUL),
        new UpstreamVector(145, 0x9e3779b9U, 0xb0a0153a8c7e9af1UL, 0x51caea60a2fd89d8UL),
        new UpstreamVector(159, 0x9e3779b9U, 0x2a77473dcb9b6ca8UL, 0x9bc3110f4be71ba6UL),
        new UpstreamVector(160, 0x9e3779b9U, 0xc7204ad1ef504c99UL, 0xee6ab4c164228930UL),
        new UpstreamVector(161, 0x9e3779b9U, 0x23db0eb67e913e55UL, 0x282e06b798bf6550UL),
        new UpstreamVector(255, 0x9e3779b9U, 0x57895b9eb6d1d97dUL, 0xaf2874624f0c3afbUL),
        new UpstreamVector(256, 0x9e3779b9U, 0x2f2ea80328d7bdc1UL, 0x7aa032d3dbb2a863UL),
        new UpstreamVector(257, 0x9e3779b9U, 0xefd48ffa556e2ce8UL, 0xd7ae097fc7f4404bUL),
        new UpstreamVector(1000, 0x9e3779b9U, 0x0ade5ffb403d37cbUL, 0xc2ebc153866e263cUL),
        new UpstreamVector(4096, 0x9e3779b9U, 0x33151f43d1f56ef9UL, 0x306c3efda27db553UL)
    ];

    // AESNI_Hash128 over the 8-byte little-endian encoding of Input.
    private static readonly UpstreamIndexVector[] UpstreamIndexVectors =
    [
        new UpstreamIndexVector(0x0000000000000000UL, 0x00000000U, 0x1c0e1ff6fbda80b2UL, 0x503ec88ed205d728UL),
        new UpstreamIndexVector(0x0000000000000001UL, 0x00000000U, 0xfbd2149ecf01febcUL, 0xe6a88a09a21fa691UL),
        new UpstreamIndexVector(0x0123456789abcdefUL, 0x00000000U, 0x068c39cfd45d6794UL, 0xadf6f9d33cc6f3bcUL),
        new UpstreamIndexVector(0xffffffffffffffffUL, 0x00000000U, 0x16da9e0b8dd238dbUL, 0xa92832d4aa667396UL),
        new UpstreamIndexVector(0x0000000000000000UL, 0x9e3779b9U, 0xa58f9652a29095eaUL, 0xbcd0afbd11853061UL),
        new UpstreamIndexVector(0x0000000000000001UL, 0x9e3779b9U, 0x5c21581c27811db9UL, 0xd6c9feabfd40aa9fUL),
        new UpstreamIndexVector(0x0123456789abcdefUL, 0x9e3779b9U, 0x156bc0c53a73acf0UL, 0xbe45995fc835fee8UL),
        new UpstreamIndexVector(0xffffffffffffffffUL, 0x9e3779b9U, 0x0cc74d29c60e7ccbUL, 0x6bd83c764716a98aUL)
    ];

    [Fact]
    public void MatchesUpstream128()
    {
        if (!AesniHash128.IsSupported)
            return;

        foreach (UpstreamVector vector in UpstreamVectors)
        {
            UInt128 hash = AesniHash128.ComputeHash(CreateData(vector.Length), vector.Seed);
            Assert.Equal(vector.Low, hash.Low);
            Assert.Equal(vector.High, hash.High);
        }
    }

    [Fact]
    public void MatchesUpstream64()
    {
        if (!AesniHash64.IsSupported)
            return;

        // Upstream's AESNI_Hash64 returns the low 64 bits of AESNI_Hash128.
        foreach (UpstreamVector vector in UpstreamVectors)
            Assert.Equal(vector.Low, AesniHash64.ComputeHash(CreateData(vector.Length), vector.Seed));
    }

    [Fact]
    public void MatchesUpstreamIndex()
    {
        if (!AesniHash128.IsSupported)
            return;

        foreach (UpstreamIndexVector vector in UpstreamIndexVectors)
        {
            UInt128 hash = AesniHash128.ComputeIndex(vector.Input, vector.Seed);
            Assert.Equal(vector.Low, hash.Low);
            Assert.Equal(vector.High, hash.High);
            Assert.Equal(vector.Low, AesniHash64.ComputeIndex(vector.Input, vector.Seed));

            if (vector.Seed == 0)
            {
                Assert.Equal(vector.Low, AesniHash128.ComputeIndex(vector.Input).Low);
                Assert.Equal(vector.Low, AesniHash64.ComputeIndex(vector.Input));
            }
        }
    }

    private static byte[] CreateData(int length)
    {
        byte[] data = new byte[length];

        for (int i = 0; i < data.Length; i++)
            data[i] = unchecked((byte)((i * 7) + 3));

        return data;
    }

    [StructLayout(LayoutKind.Auto)]
    private readonly record struct UpstreamVector(int Length, uint Seed, ulong Low, ulong High);

    [StructLayout(LayoutKind.Auto)]
    private readonly record struct UpstreamIndexVector(ulong Input, uint Seed, ulong Low, ulong High);
}