using System.Buffers.Binary;
using System.Runtime.InteropServices;
using Genbox.FastHash.RapidHash;

namespace Genbox.FastHash.Tests.Single;

public class Rapid3HashTests
{
    private static readonly byte[] QuickFox = "The quick brown fox jumps over the lazy dog"u8.ToArray();
    private static readonly byte[] Hello = "hello"u8.ToArray();
    private static readonly byte[] HelloWorld = "hello world"u8.ToArray();
    private static readonly byte[] Zeros1000 = new byte[1000];

    private static readonly Vector[] Vectors =
    [
        new Vector([], 0, 0x0338dc4be2cecdaeUL),
        new Vector("a"u8.ToArray(), 0, 0x599f47df33a2e1ebUL),
        new Vector(Hello, 0, 0x2e2d7651b45f7946UL),
        new Vector(HelloWorld, 0, 0x2f27cb27d5240940UL),
        new Vector(QuickFox, 0, 0x91722dc8d52a3f7bUL),
        new Vector(Zeros1000, 0, 0x1a2f2e1ba3bc17dcUL),
        new Vector([], 123, 0xdff2041cce4be562UL),
        new Vector("a"u8.ToArray(), 123, 0x5512cb31e97c34a7UL),
        new Vector(Hello, 123, 0xf31c541b486d28aeUL),
        new Vector(HelloWorld, 123, 0x686b8e902b13032eUL),
        new Vector(QuickFox, 123, 0x0896531731a6844eUL),
        new Vector(Zeros1000, 123, 0xd1f8a452e032c247UL)
    ];

    // Generated by compiling upstream rapidhash.h (bc4b4ba, default RAPIDHASH_FAST; COMPACT and UNROLLED agree)
    // and calling rapidhash_withSeed/rapidhashMicro_withSeed/rapidhashNano_withSeed over CreateData(length).
    // Lengths cover every branch: <=16 byte paths, the 16-byte step chain, and the 48/80/112/224-byte loops.
    private static readonly UpstreamVector[] UpstreamRapidVectors =
    [
        new UpstreamVector(0, 0x0000000000000000UL, 0x0338dc4be2cecdaeUL),
        new UpstreamVector(1, 0x0000000000000000UL, 0xc6939e8fb00709ffUL),
        new UpstreamVector(2, 0x0000000000000000UL, 0xad801a47df89b990UL),
        new UpstreamVector(3, 0x0000000000000000UL, 0x5655e9f764e8fb47UL),
        new UpstreamVector(4, 0x0000000000000000UL, 0x49227fb2f401a8fcUL),
        new UpstreamVector(5, 0x0000000000000000UL, 0x01b87dc529f9affeUL),
        new UpstreamVector(7, 0x0000000000000000UL, 0xf8d2bdfe7f388df8UL),
        new UpstreamVector(8, 0x0000000000000000UL, 0xf5980b646f822e89UL),
        new UpstreamVector(9, 0x0000000000000000UL, 0xfd9787420766dd08UL),
        new UpstreamVector(15, 0x0000000000000000UL, 0x71bb053c322ab7cbUL),
        new UpstreamVector(16, 0x0000000000000000UL, 0xd0e68844cb24a480UL),
        new UpstreamVector(17, 0x0000000000000000UL, 0x7998c836066e171bUL),
        new UpstreamVector(31, 0x0000000000000000UL, 0xed3eee46cfa04e29UL),
        new UpstreamVector(32, 0x0000000000000000UL, 0x4f6a424c80f09818UL),
        new UpstreamVector(33, 0x0000000000000000UL, 0x50f708a727e0a6f9UL),
        new UpstreamVector(47, 0x0000000000000000UL, 0x5fa1ee593a9d44e5UL),
        new UpstreamVector(48, 0x0000000000000000UL, 0x78e892266d502576UL),
        new UpstreamVector(49, 0x0000000000000000UL, 0x4c6d34cc323274b4UL),
        new UpstreamVector(63, 0x0000000000000000UL, 0x4c285a4e89ff72c0UL),
        new UpstreamVector(64, 0x0000000000000000UL, 0xd5e007f01f191991UL),
        new UpstreamVector(65, 0x0000000000000000UL, 0xff190630cc567eb0UL),
        new UpstreamVector(79, 0x0000000000000000UL, 0xf4f386be68685275UL),
        new UpstreamVector(80, 0x0000000000000000UL, 0x760884c469b5878aUL),
        new UpstreamVector(81, 0x0000000000000000UL, 0xc076ee2566934dfdUL),
        new UpstreamVector(95, 0x0000000000000000UL, 0xb3854ad658cb108dUL),
        new UpstreamVector(96, 0x0000000000000000UL, 0x159e3a5cc100d66dUL),
        new UpstreamVector(97, 0x0000000000000000UL, 0x223a2bc11ff709c2UL),
        new UpstreamVector(111, 0x0000000000000000UL, 0xb6d3e4e8971bb81aUL),
        new UpstreamVector(112, 0x0000000000000000UL, 0xbde27e659c073097UL),
        new UpstreamVector(113, 0x0000000000000000UL, 0xe7198c47a15df67fUL),
        new UpstreamVector(127, 0x0000000000000000UL, 0x67ba7238e8cfa242UL),
        new UpstreamVector(128, 0x0000000000000000UL, 0x29165d219dbca0aeUL),
        new UpstreamVector(159, 0x0000000000000000UL, 0xc55bc8a81275f380UL),
        new UpstreamVector(160, 0x0000000000000000UL, 0xd628b63d1a9cb5bbUL),
        new UpstreamVector(161, 0x0000000000000000UL, 0x5b6535193414e0a1UL),
        new UpstreamVector(223, 0x0000000000000000UL, 0xaea4599b59c53f99UL),
        new UpstreamVector(224, 0x0000000000000000UL, 0xcc2f57413b929cf1UL),
        new UpstreamVector(225, 0x0000000000000000UL, 0x9fe6788088459d9fUL),
        new UpstreamVector(239, 0x0000000000000000UL, 0xbed8d77a0aa76dd1UL),
        new UpstreamVector(240, 0x0000000000000000UL, 0xcb449ee161dbb311UL),
        new UpstreamVector(241, 0x0000000000000000UL, 0xe008b755fc623c39UL),
        new UpstreamVector(335, 0x0000000000000000UL, 0x554dd4c7d367d140UL),
        new UpstreamVector(336, 0x0000000000000000UL, 0x821feac408e58c1eUL),
        new UpstreamVector(337, 0x0000000000000000UL, 0x2531f7beeb8777a1UL),
        new UpstreamVector(447, 0x0000000000000000UL, 0x22f8424a6d8076f9UL),
        new UpstreamVector(448, 0x0000000000000000UL, 0xdeffb343d95a47d8UL),
        new UpstreamVector(449, 0x0000000000000000UL, 0x8b87cd1acaa2e61cUL),
        new UpstreamVector(1000, 0x0000000000000000UL, 0x871e919aec95c844UL),
        new UpstreamVector(4096, 0x0000000000000000UL, 0xbf6eb5fe093aeb09UL),
        new UpstreamVector(0, 0x0123456789abcdefUL, 0x565ef32cd8efb3ddUL),
        new UpstreamVector(1, 0x0123456789abcdefUL, 0x5ed83e2608fc233eUL),
        new UpstreamVector(2, 0x0123456789abcdefUL, 0x4051a9439961052bUL),
        new UpstreamVector(3, 0x0123456789abcdefUL, 0xc82eb9221b53d004UL),
        new UpstreamVector(4, 0x0123456789abcdefUL, 0xd8148f849747ec09UL),
        new UpstreamVector(5, 0x0123456789abcdefUL, 0xf9dea057a2d174feUL),
        new UpstreamVector(7, 0x0123456789abcdefUL, 0x15ed25ef16203477UL),
        new UpstreamVector(8, 0x0123456789abcdefUL, 0x18266e9028777fa7UL),
        new UpstreamVector(9, 0x0123456789abcdefUL, 0x27dcc8fa30fda633UL),
        new UpstreamVector(15, 0x0123456789abcdefUL, 0xde8ee23860e293e6UL),
        new UpstreamVector(16, 0x0123456789abcdefUL, 0x020311d9259b9e9eUL),
        new UpstreamVector(17, 0x0123456789abcdefUL, 0x0f6db5ecf711d100UL),
        new UpstreamVector(31, 0x0123456789abcdefUL, 0x0c4187b2dabc1b54UL),
        new UpstreamVector(32, 0x0123456789abcdefUL, 0x4458222399725cc3UL),
        new UpstreamVector(33, 0x0123456789abcdefUL, 0x95723ea9a41bf3d7UL),
        new UpstreamVector(47, 0x0123456789abcdefUL, 0x836712ff3b012d08UL),
        new UpstreamVector(48, 0x0123456789abcdefUL, 0x4d155e31fbf3ddbcUL),
        new UpstreamVector(49, 0x0123456789abcdefUL, 0xfbb6bd7d1f736942UL),
        new UpstreamVector(63, 0x0123456789abcdefUL, 0xd6576475626cc431UL),
        new UpstreamVector(64, 0x0123456789abcdefUL, 0xcb377d5b1382b919UL),
        new UpstreamVector(65, 0x0123456789abcdefUL, 0xacc4fb2b0fec09daUL),
        new UpstreamVector(79, 0x0123456789abcdefUL, 0x075f26d99db32a7bUL),
        new UpstreamVector(80, 0x0123456789abcdefUL, 0xd0406a5b102fcc84UL),
        new UpstreamVector(81, 0x0123456789abcdefUL, 0x18c6d955dc20f758UL),
        new UpstreamVector(95, 0x0123456789abcdefUL, 0x85209e611c60714cUL),
        new UpstreamVector(96, 0x0123456789abcdefUL, 0xceb7cae742993f1fUL),
        new UpstreamVector(97, 0x0123456789abcdefUL, 0xd2e68416b0680090UL),
        new UpstreamVector(111, 0x0123456789abcdefUL, 0x2d02ed347be383c7UL),
        new UpstreamVector(112, 0x0123456789abcdefUL, 0x29adea8005b9c81fUL),
        new UpstreamVector(113, 0x0123456789abcdefUL, 0xa94ec7588f15b658UL),
        new UpstreamVector(127, 0x0123456789abcdefUL, 0x0c5f9df43c85d3ebUL),
        new UpstreamVector(128, 0x0123456789abcdefUL, 0x044586432c4522f0UL),
        new UpstreamVector(159, 0x0123456789abcdefUL, 0x08a81702da0dcbd1UL),
        new UpstreamVector(160, 0x0123456789abcdefUL, 0xd05633b875c6f765UL),
        new UpstreamVector(161, 0x0123456789abcdefUL, 0x74a19741b2c4ec3dUL),
        new UpstreamVector(223, 0x0123456789abcdefUL, 0x1d6be22898328590UL),
        new UpstreamVector(224, 0x0123456789abcdefUL, 0x38ce16a8c700499cUL),
        new UpstreamVector(225, 0x0123456789abcdefUL, 0x59a1d28380df861bUL),
        new UpstreamVector(239, 0x0123456789abcdefUL, 0x21f86154f443d83cUL),
        new UpstreamVector(240, 0x0123456789abcdefUL, 0x74fab3829209d30eUL),
        new UpstreamVector(241, 0x0123456789abcdefUL, 0x894654283e3d7fa9UL),
        new UpstreamVector(335, 0x0123456789abcdefUL, 0x8713537fa621d721UL),
        new UpstreamVector(336, 0x0123456789abcdefUL, 0x0b03f5c5f7d62bfbUL),
        new UpstreamVector(337, 0x0123456789abcdefUL, 0xfa561eb7c551e669UL),
        new UpstreamVector(447, 0x0123456789abcdefUL, 0x477fd268b756ea42UL),
        new UpstreamVector(448, 0x0123456789abcdefUL, 0x421bd0a9d986a49aUL),
        new UpstreamVector(449, 0x0123456789abcdefUL, 0xc0528be1791990dcUL),
        new UpstreamVector(1000, 0x0123456789abcdefUL, 0x648a7e26f404e913UL),
        new UpstreamVector(4096, 0x0123456789abcdefUL, 0x06245bf066c9fe6aUL)
    ];

    private static readonly UpstreamVector[] UpstreamMicroVectors =
    [
        new UpstreamVector(0, 0x0000000000000000UL, 0x0338dc4be2cecdaeUL),
        new UpstreamVector(1, 0x0000000000000000UL, 0xc6939e8fb00709ffUL),
        new UpstreamVector(2, 0x0000000000000000UL, 0xad801a47df89b990UL),
        new UpstreamVector(3, 0x0000000000000000UL, 0x5655e9f764e8fb47UL),
        new UpstreamVector(4, 0x0000000000000000UL, 0x49227fb2f401a8fcUL),
        new UpstreamVector(5, 0x0000000000000000UL, 0x01b87dc529f9affeUL),
        new UpstreamVector(7, 0x0000000000000000UL, 0xf8d2bdfe7f388df8UL),
        new UpstreamVector(8, 0x0000000000000000UL, 0xf5980b646f822e89UL),
        new UpstreamVector(9, 0x0000000000000000UL, 0xfd9787420766dd08UL),
        new UpstreamVector(15, 0x0000000000000000UL, 0x71bb053c322ab7cbUL),
        new UpstreamVector(16, 0x0000000000000000UL, 0xd0e68844cb24a480UL),
        new UpstreamVector(17, 0x0000000000000000UL, 0x7998c836066e171bUL),
        new UpstreamVector(31, 0x0000000000000000UL, 0xed3eee46cfa04e29UL),
        new UpstreamVector(32, 0x0000000000000000UL, 0x4f6a424c80f09818UL),
        new UpstreamVector(33, 0x0000000000000000UL, 0x50f708a727e0a6f9UL),
        new UpstreamVector(47, 0x0000000000000000UL, 0x5fa1ee593a9d44e5UL),
        new UpstreamVector(48, 0x0000000000000000UL, 0x78e892266d502576UL),
        new UpstreamVector(49, 0x0000000000000000UL, 0x4c6d34cc323274b4UL),
        new UpstreamVector(63, 0x0000000000000000UL, 0x4c285a4e89ff72c0UL),
        new UpstreamVector(64, 0x0000000000000000UL, 0xd5e007f01f191991UL),
        new UpstreamVector(65, 0x0000000000000000UL, 0xff190630cc567eb0UL),
        new UpstreamVector(79, 0x0000000000000000UL, 0xf4f386be68685275UL),
        new UpstreamVector(80, 0x0000000000000000UL, 0x760884c469b5878aUL),
        new UpstreamVector(81, 0x0000000000000000UL, 0x4ca76e386d6c89a1UL),
        new UpstreamVector(95, 0x0000000000000000UL, 0xce9fbd2f1896d473UL),
        new UpstreamVector(96, 0x0000000000000000UL, 0x4e60db3b66677e91UL),
        new UpstreamVector(97, 0x0000000000000000UL, 0x478bb96b39af7214UL),
        new UpstreamVector(111, 0x0000000000000000UL, 0x7b28d88f6ffce214UL),
        new UpstreamVector(112, 0x0000000000000000UL, 0xb5a9af92e3352a6fUL),
        new UpstreamVector(113, 0x0000000000000000UL, 0x0f39e44d0b4ab62aUL),
        new UpstreamVector(127, 0x0000000000000000UL, 0x5ced9f2291a7def7UL),
        new UpstreamVector(128, 0x0000000000000000UL, 0xca8e347f73afa7f7UL),
        new UpstreamVector(159, 0x0000000000000000UL, 0xa9ab67ac4ebcfd86UL),
        new UpstreamVector(160, 0x0000000000000000UL, 0xed4ecdefe9d92580UL),
        new UpstreamVector(161, 0x0000000000000000UL, 0x2842a920118cbbe3UL),
        new UpstreamVector(223, 0x0000000000000000UL, 0x9632ec1cddb0ad4dUL),
        new UpstreamVector(224, 0x0000000000000000UL, 0x3cd166106c97249eUL),
        new UpstreamVector(225, 0x0000000000000000UL, 0xe1a2748eb4c8cc27UL),
        new UpstreamVector(239, 0x0000000000000000UL, 0xcbdb869f90d83ffdUL),
        new UpstreamVector(240, 0x0000000000000000UL, 0x0544ee71644685a7UL),
        new UpstreamVector(241, 0x0000000000000000UL, 0x7640da1eeb9f9844UL),
        new UpstreamVector(335, 0x0000000000000000UL, 0xfda47d1358d058a4UL),
        new UpstreamVector(336, 0x0000000000000000UL, 0x4c274a8b44f225e4UL),
        new UpstreamVector(337, 0x0000000000000000UL, 0x20f4d9e1a0ae9e3bUL),
        new UpstreamVector(447, 0x0000000000000000UL, 0x23a2fc5051a02dc6UL),
        new UpstreamVector(448, 0x0000000000000000UL, 0x0cfad2d45abf9596UL),
        new UpstreamVector(449, 0x0000000000000000UL, 0x4d4de5511fe56b4aUL),
        new UpstreamVector(1000, 0x0000000000000000UL, 0x8220ef4e1b425b9fUL),
        new UpstreamVector(4096, 0x0000000000000000UL, 0x1265bb6f3aa81dafUL),
        new UpstreamVector(0, 0x0123456789abcdefUL, 0x565ef32cd8efb3ddUL),
        new UpstreamVector(1, 0x0123456789abcdefUL, 0x5ed83e2608fc233eUL),
        new UpstreamVector(2, 0x0123456789abcdefUL, 0x4051a9439961052bUL),
        new UpstreamVector(3, 0x0123456789abcdefUL, 0xc82eb9221b53d004UL),
        new UpstreamVector(4, 0x0123456789abcdefUL, 0xd8148f849747ec09UL),
        new UpstreamVector(5, 0x0123456789abcdefUL, 0xf9dea057a2d174feUL),
        new UpstreamVector(7, 0x0123456789abcdefUL, 0x15ed25ef16203477UL),
        new UpstreamVector(8, 0x0123456789abcdefUL, 0x18266e9028777fa7UL),
        new UpstreamVector(9, 0x0123456789abcdefUL, 0x27dcc8fa30fda633UL),
        new UpstreamVector(15, 0x0123456789abcdefUL, 0xde8ee23860e293e6UL),
        new UpstreamVector(16, 0x0123456789abcdefUL, 0x020311d9259b9e9eUL),
        new UpstreamVector(17, 0x0123456789abcdefUL, 0x0f6db5ecf711d100UL),
        new UpstreamVector(31, 0x0123456789abcdefUL, 0x0c4187b2dabc1b54UL),
        new UpstreamVector(32, 0x0123456789abcdefUL, 0x4458222399725cc3UL),
        new UpstreamVector(33, 0x0123456789abcdefUL, 0x95723ea9a41bf3d7UL),
        new UpstreamVector(47, 0x0123456789abcdefUL, 0x836712ff3b012d08UL),
        new UpstreamVector(48, 0x0123456789abcdefUL, 0x4d155e31fbf3ddbcUL),
        new UpstreamVector(49, 0x0123456789abcdefUL, 0xfbb6bd7d1f736942UL),
        new UpstreamVector(63, 0x0123456789abcdefUL, 0xd6576475626cc431UL),
        new UpstreamVector(64, 0x0123456789abcdefUL, 0xcb377d5b1382b919UL),
        new UpstreamVector(65, 0x0123456789abcdefUL, 0xacc4fb2b0fec09daUL),
        new UpstreamVector(79, 0x0123456789abcdefUL, 0x075f26d99db32a7bUL),
        new UpstreamVector(80, 0x0123456789abcdefUL, 0xd0406a5b102fcc84UL),
        new UpstreamVector(81, 0x0123456789abcdefUL, 0x8b2b366477698367UL),
        new UpstreamVector(95, 0x0123456789abcdefUL, 0xb841d9fb380938b6UL),
        new UpstreamVector(96, 0x0123456789abcdefUL, 0x91ec7f24f08322faUL),
        new UpstreamVector(97, 0x0123456789abcdefUL, 0x297810a4049e4ff9UL),
        new UpstreamVector(111, 0x0123456789abcdefUL, 0x41c9bf615b371786UL),
        new UpstreamVector(112, 0x0123456789abcdefUL, 0x4f3e15f4bdd4b548UL),
        new UpstreamVector(113, 0x0123456789abcdefUL, 0x1b6024b3a96eaf5bUL),
        new UpstreamVector(127, 0x0123456789abcdefUL, 0x4aff4ffbd6a5b3e5UL),
        new UpstreamVector(128, 0x0123456789abcdefUL, 0x169a6f93094a6b0cUL),
        new UpstreamVector(159, 0x0123456789abcdefUL, 0x2cb1790a0f0086a4UL),
        new UpstreamVector(160, 0x0123456789abcdefUL, 0x2f2cdfef33bb24f8UL),
        new UpstreamVector(161, 0x0123456789abcdefUL, 0x869ccd5519d9dc23UL),
        new UpstreamVector(223, 0x0123456789abcdefUL, 0x4e0d1d3c61f790d9UL),
        new UpstreamVector(224, 0x0123456789abcdefUL, 0x8ee5593809985eb0UL),
        new UpstreamVector(225, 0x0123456789abcdefUL, 0x4005a7e9b62a0059UL),
        new UpstreamVector(239, 0x0123456789abcdefUL, 0x4ce47c33f5496f9bUL),
        new UpstreamVector(240, 0x0123456789abcdefUL, 0x0bab9e4dd0f3b517UL),
        new UpstreamVector(241, 0x0123456789abcdefUL, 0x55ac14ee069d7bffUL),
        new UpstreamVector(335, 0x0123456789abcdefUL, 0x564b3a0120951f8cUL),
        new UpstreamVector(336, 0x0123456789abcdefUL, 0x6ef98394e0eaf307UL),
        new UpstreamVector(337, 0x0123456789abcdefUL, 0xad0c2157435f8575UL),
        new UpstreamVector(447, 0x0123456789abcdefUL, 0xbce9f1b27e1ec6b9UL),
        new UpstreamVector(448, 0x0123456789abcdefUL, 0x1528ad3340f606b4UL),
        new UpstreamVector(449, 0x0123456789abcdefUL, 0x3b1b5e97a786e002UL),
        new UpstreamVector(1000, 0x0123456789abcdefUL, 0x99d7b1b9b248deadUL),
        new UpstreamVector(4096, 0x0123456789abcdefUL, 0x0e261d4866ce3837UL)
    ];

    private static readonly UpstreamVector[] UpstreamNanoVectors =
    [
        new UpstreamVector(0, 0x0000000000000000UL, 0x0338dc4be2cecdaeUL),
        new UpstreamVector(1, 0x0000000000000000UL, 0xc6939e8fb00709ffUL),
        new UpstreamVector(2, 0x0000000000000000UL, 0xad801a47df89b990UL),
        new UpstreamVector(3, 0x0000000000000000UL, 0x5655e9f764e8fb47UL),
        new UpstreamVector(4, 0x0000000000000000UL, 0x49227fb2f401a8fcUL),
        new UpstreamVector(5, 0x0000000000000000UL, 0x01b87dc529f9affeUL),
        new UpstreamVector(7, 0x0000000000000000UL, 0xf8d2bdfe7f388df8UL),
        new UpstreamVector(8, 0x0000000000000000UL, 0xf5980b646f822e89UL),
        new UpstreamVector(9, 0x0000000000000000UL, 0xfd9787420766dd08UL),
        new UpstreamVector(15, 0x0000000000000000UL, 0x71bb053c322ab7cbUL),
        new UpstreamVector(16, 0x0000000000000000UL, 0xd0e68844cb24a480UL),
        new UpstreamVector(17, 0x0000000000000000UL, 0x7998c836066e171bUL),
        new UpstreamVector(31, 0x0000000000000000UL, 0xed3eee46cfa04e29UL),
        new UpstreamVector(32, 0x0000000000000000UL, 0x4f6a424c80f09818UL),
        new UpstreamVector(33, 0x0000000000000000UL, 0x50f708a727e0a6f9UL),
        new UpstreamVector(47, 0x0000000000000000UL, 0x5fa1ee593a9d44e5UL),
        new UpstreamVector(48, 0x0000000000000000UL, 0x78e892266d502576UL),
        new UpstreamVector(49, 0x0000000000000000UL, 0x3b64ec2b4166561cUL),
        new UpstreamVector(63, 0x0000000000000000UL, 0xa9e044140b88fd56UL),
        new UpstreamVector(64, 0x0000000000000000UL, 0x11b563e267e1cafdUL),
        new UpstreamVector(65, 0x0000000000000000UL, 0x9b0938534aca8803UL),
        new UpstreamVector(79, 0x0000000000000000UL, 0xbcec4ea2f5c6ae4aUL),
        new UpstreamVector(80, 0x0000000000000000UL, 0xdd71b6a306e735faUL),
        new UpstreamVector(81, 0x0000000000000000UL, 0x0f6fbb708b8c09f3UL),
        new UpstreamVector(95, 0x0000000000000000UL, 0x4a66ebb963f9ad24UL),
        new UpstreamVector(96, 0x0000000000000000UL, 0x3d8753f5dc138edaUL),
        new UpstreamVector(97, 0x0000000000000000UL, 0xd6c65a4eb45c2282UL),
        new UpstreamVector(111, 0x0000000000000000UL, 0xbbc7928cc2933434UL),
        new UpstreamVector(112, 0x0000000000000000UL, 0xff2941f6d8b802deUL),
        new UpstreamVector(113, 0x0000000000000000UL, 0x8c8986cac110e515UL),
        new UpstreamVector(127, 0x0000000000000000UL, 0xef6e25ea90e92dadUL),
        new UpstreamVector(128, 0x0000000000000000UL, 0xb5e9b5cc7dcaac79UL),
        new UpstreamVector(159, 0x0000000000000000UL, 0xd3d420841e753ca2UL),
        new UpstreamVector(160, 0x0000000000000000UL, 0xde2097b4223c1d23UL),
        new UpstreamVector(161, 0x0000000000000000UL, 0x566e4480fbafbd1cUL),
        new UpstreamVector(223, 0x0000000000000000UL, 0xc7a5a3e0b2121b47UL),
        new UpstreamVector(224, 0x0000000000000000UL, 0x9e855befb8e6490cUL),
        new UpstreamVector(225, 0x0000000000000000UL, 0xbf2af011d4a35702UL),
        new UpstreamVector(239, 0x0000000000000000UL, 0xc42aa836bf870fabUL),
        new UpstreamVector(240, 0x0000000000000000UL, 0x606ae9bec2f3a05fUL),
        new UpstreamVector(241, 0x0000000000000000UL, 0xf2bc636d6dc8ff48UL),
        new UpstreamVector(335, 0x0000000000000000UL, 0x4a0ad5cec9830241UL),
        new UpstreamVector(336, 0x0000000000000000UL, 0x76537c469e503e56UL),
        new UpstreamVector(337, 0x0000000000000000UL, 0xe60abd831907c564UL),
        new UpstreamVector(447, 0x0000000000000000UL, 0x1d66828b1dab154eUL),
        new UpstreamVector(448, 0x0000000000000000UL, 0xbbe53bd9cdb65d13UL),
        new UpstreamVector(449, 0x0000000000000000UL, 0x261bc21a5eeb6bd4UL),
        new UpstreamVector(1000, 0x0000000000000000UL, 0x66ab9ae6bea910d1UL),
        new UpstreamVector(4096, 0x0000000000000000UL, 0xc1657516ff38d332UL),
        new UpstreamVector(0, 0x0123456789abcdefUL, 0x565ef32cd8efb3ddUL),
        new UpstreamVector(1, 0x0123456789abcdefUL, 0x5ed83e2608fc233eUL),
        new UpstreamVector(2, 0x0123456789abcdefUL, 0x4051a9439961052bUL),
        new UpstreamVector(3, 0x0123456789abcdefUL, 0xc82eb9221b53d004UL),
        new UpstreamVector(4, 0x0123456789abcdefUL, 0xd8148f849747ec09UL),
        new UpstreamVector(5, 0x0123456789abcdefUL, 0xf9dea057a2d174feUL),
        new UpstreamVector(7, 0x0123456789abcdefUL, 0x15ed25ef16203477UL),
        new UpstreamVector(8, 0x0123456789abcdefUL, 0x18266e9028777fa7UL),
        new UpstreamVector(9, 0x0123456789abcdefUL, 0x27dcc8fa30fda633UL),
        new UpstreamVector(15, 0x0123456789abcdefUL, 0xde8ee23860e293e6UL),
        new UpstreamVector(16, 0x0123456789abcdefUL, 0x020311d9259b9e9eUL),
        new UpstreamVector(17, 0x0123456789abcdefUL, 0x0f6db5ecf711d100UL),
        new UpstreamVector(31, 0x0123456789abcdefUL, 0x0c4187b2dabc1b54UL),
        new UpstreamVector(32, 0x0123456789abcdefUL, 0x4458222399725cc3UL),
        new UpstreamVector(33, 0x0123456789abcdefUL, 0x95723ea9a41bf3d7UL),
        new UpstreamVector(47, 0x0123456789abcdefUL, 0x836712ff3b012d08UL),
        new UpstreamVector(48, 0x0123456789abcdefUL, 0x4d155e31fbf3ddbcUL),
        new UpstreamVector(49, 0x0123456789abcdefUL, 0x843f6c16feaa421eUL),
        new UpstreamVector(63, 0x0123456789abcdefUL, 0x1f1813b658f750ecUL),
        new UpstreamVector(64, 0x0123456789abcdefUL, 0x7f2c05ce34903c7bUL),
        new UpstreamVector(65, 0x0123456789abcdefUL, 0x51f8d325878818c1UL),
        new UpstreamVector(79, 0x0123456789abcdefUL, 0xd3acc6660a8c4e25UL),
        new UpstreamVector(80, 0x0123456789abcdefUL, 0xc95d53f7ee8a7d88UL),
        new UpstreamVector(81, 0x0123456789abcdefUL, 0xa4a9fdb6f59909d8UL),
        new UpstreamVector(95, 0x0123456789abcdefUL, 0x41a6ce7e11efcc4eUL),
        new UpstreamVector(96, 0x0123456789abcdefUL, 0xd8c7d687ede0bd2bUL),
        new UpstreamVector(97, 0x0123456789abcdefUL, 0x77bf779e69ba6d67UL),
        new UpstreamVector(111, 0x0123456789abcdefUL, 0x6466403d907fdcddUL),
        new UpstreamVector(112, 0x0123456789abcdefUL, 0x4b010a1f3185e8d5UL),
        new UpstreamVector(113, 0x0123456789abcdefUL, 0x3b9638845689bbecUL),
        new UpstreamVector(127, 0x0123456789abcdefUL, 0x5c6840a1a24f510fUL),
        new UpstreamVector(128, 0x0123456789abcdefUL, 0xb8a6156331a1099fUL),
        new UpstreamVector(159, 0x0123456789abcdefUL, 0x78cdd9665c12f3ecUL),
        new UpstreamVector(160, 0x0123456789abcdefUL, 0xab15c49be5a2ad33UL),
        new UpstreamVector(161, 0x0123456789abcdefUL, 0xce5b3caa1efb8133UL),
        new UpstreamVector(223, 0x0123456789abcdefUL, 0x4c5669aa5a888172UL),
        new UpstreamVector(224, 0x0123456789abcdefUL, 0xf6d93479caddb2aaUL),
        new UpstreamVector(225, 0x0123456789abcdefUL, 0xca941b1b7ee7d99aUL),
        new UpstreamVector(239, 0x0123456789abcdefUL, 0xe089a3ed7e6a2dd9UL),
        new UpstreamVector(240, 0x0123456789abcdefUL, 0xc0fd661eb3488562UL),
        new UpstreamVector(241, 0x0123456789abcdefUL, 0x6fe8a2981d44c639UL),
        new UpstreamVector(335, 0x0123456789abcdefUL, 0xf1cfd47e30cbd7b7UL),
        new UpstreamVector(336, 0x0123456789abcdefUL, 0x3849766295d7ed49UL),
        new UpstreamVector(337, 0x0123456789abcdefUL, 0xa0e253407f31473eUL),
        new UpstreamVector(447, 0x0123456789abcdefUL, 0xfedbbac2abd3e082UL),
        new UpstreamVector(448, 0x0123456789abcdefUL, 0x6dbd6528ef884f05UL),
        new UpstreamVector(449, 0x0123456789abcdefUL, 0x5523cd40f13cc2eeUL),
        new UpstreamVector(1000, 0x0123456789abcdefUL, 0x011bf43c7a768900UL),
        new UpstreamVector(4096, 0x0123456789abcdefUL, 0x9921cb2f9cd662d7UL)
    ];

    // rapidhash_withSeed over the 8-byte little-endian encoding of Input.
    private static readonly UpstreamIndexVector[] UpstreamIndexVectors =
    [
        new UpstreamIndexVector(0x0000000000000000UL, 0x0000000000000000UL, 0x9efc171aebcea1f3UL),
        new UpstreamIndexVector(0x0000000000000001UL, 0x0000000000000000UL, 0xbec178309f44afbcUL),
        new UpstreamIndexVector(0x0123456789abcdefUL, 0x0000000000000000UL, 0xfdc89f6eae2b0443UL),
        new UpstreamIndexVector(0xffffffffffffffffUL, 0x0000000000000000UL, 0x8a185fbd8550916dUL),
        new UpstreamIndexVector(0x0000000000000000UL, 0x0123456789abcdefUL, 0x7d82fdcf5bab70caUL),
        new UpstreamIndexVector(0x0000000000000001UL, 0x0123456789abcdefUL, 0x2d5dcceb72a848cdUL),
        new UpstreamIndexVector(0x0123456789abcdefUL, 0x0123456789abcdefUL, 0x159ac8c3014079deUL),
        new UpstreamIndexVector(0xffffffffffffffffUL, 0x0123456789abcdefUL, 0x2a27e9c678e066c6UL)
    ];

    [Fact]
    public void TestVectors()
    {
        foreach (Vector vector in Vectors)
            Assert.Equal(vector.Expected, Rapid3Hash64.ComputeHash(vector.Data, vector.Seed));
    }

    [Fact]
    public void MatchesUpstreamRapid()
    {
        foreach (UpstreamVector vector in UpstreamRapidVectors)
            Assert.Equal(vector.Expected, Rapid3Hash64.ComputeHash(CreateData(vector.Length), vector.Seed));
    }

    [Fact]
    public void MatchesUpstreamMicro()
    {
        foreach (UpstreamVector vector in UpstreamMicroVectors)
            Assert.Equal(vector.Expected, Rapid3HashMicro64.ComputeHash(CreateData(vector.Length), vector.Seed));
    }

    [Fact]
    public void MatchesUpstreamNano()
    {
        foreach (UpstreamVector vector in UpstreamNanoVectors)
            Assert.Equal(vector.Expected, Rapid3HashNano64.ComputeHash(CreateData(vector.Length), vector.Seed));
    }

    [Fact]
    public void MatchesUpstreamIndex()
    {
        foreach (UpstreamIndexVector vector in UpstreamIndexVectors)
        {
            Assert.Equal(vector.Expected, Rapid3Hash64.ComputeIndex(vector.Input, vector.Seed));
            Assert.Equal(vector.Expected, Rapid3HashMicro64.ComputeIndex(vector.Input, vector.Seed));
            Assert.Equal(vector.Expected, Rapid3HashNano64.ComputeIndex(vector.Input, vector.Seed));

            if (vector.Seed == 0)
            {
                Assert.Equal(vector.Expected, Rapid3Hash64.ComputeIndex(vector.Input));
                Assert.Equal(vector.Expected, Rapid3HashMicro64.ComputeIndex(vector.Input));
                Assert.Equal(vector.Expected, Rapid3HashNano64.ComputeIndex(vector.Input));
            }
        }
    }

    [Fact]
    public void ComputeIndexMatchesByteHash()
    {
        ulong[] inputs =
        [
            0UL,
            1UL,
            0x0123456789abcdefUL,
            12808224424451380151UL,
            ulong.MaxValue
        ];

        Span<byte> data = stackalloc byte[8];

        foreach (ulong input in inputs)
        {
            BinaryPrimitives.WriteUInt64LittleEndian(data, input);

            Assert.Equal(Rapid3Hash64.ComputeHash(data), Rapid3Hash64.ComputeIndex(input));
            Assert.Equal(Rapid3Hash64.ComputeHash(data, 123), Rapid3Hash64.ComputeIndex(input, 123));
        }
    }

    [Fact]
    public void MicroMatchesRapidForShortInputs()
    {
        byte[][] inputs =
        [
            [],
            "a"u8.ToArray(),
            Hello,
            HelloWorld,
            QuickFox
        ];

        foreach (byte[] data in inputs)
        {
            Assert.Equal(Rapid3Hash64.ComputeHash(data), Rapid3HashMicro64.ComputeHash(data));
            Assert.Equal(Rapid3Hash64.ComputeHash(data, 123), Rapid3HashMicro64.ComputeHash(data, 123));
        }
    }

    [Fact]
    public void NanoMatchesRapidForShortInputs()
    {
        byte[][] inputs =
        [
            [],
            "a"u8.ToArray(),
            Hello,
            HelloWorld
        ];

        foreach (byte[] data in inputs)
        {
            Assert.Equal(Rapid3Hash64.ComputeHash(data), Rapid3HashNano64.ComputeHash(data));
            Assert.Equal(Rapid3Hash64.ComputeHash(data, 123), Rapid3HashNano64.ComputeHash(data, 123));
        }
    }

    [Fact]
    public void MicroAndNanoRespectSeedOnLongInput()
    {
        ulong micro0 = Rapid3HashMicro64.ComputeHash(Zeros1000);
        ulong micro1 = Rapid3HashMicro64.ComputeHash(Zeros1000, 123);
        ulong nano0 = Rapid3HashNano64.ComputeHash(Zeros1000);
        ulong nano1 = Rapid3HashNano64.ComputeHash(Zeros1000, 123);

        Assert.NotEqual(micro0, micro1);
        Assert.NotEqual(nano0, nano1);
    }

    private static byte[] CreateData(int length)
    {
        byte[] data = new byte[length];

        for (int i = 0; i < data.Length; i++)
            data[i] = unchecked((byte)((i * 7) + 3));

        return data;
    }

    private readonly record struct Vector(byte[] Data, ulong Seed, ulong Expected);

    [StructLayout(LayoutKind.Auto)]
    private readonly record struct UpstreamVector(int Length, ulong Seed, ulong Expected);

    [StructLayout(LayoutKind.Auto)]
    private readonly record struct UpstreamIndexVector(ulong Input, ulong Seed, ulong Expected);
}