name: Generic build

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - 'main'

env:
  DOTNET_EnableDiagnostics: 0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Setup pinned .NET SDK
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: Src/**/packages.lock.json
      - name: Build
        shell: pwsh
        run: |
          ./Scripts/Build.ps1